Feature/mp3 converter
readdle/RDMPEG pull request #1
Opened 2020-07-07 09:16 UTC by rdmeleshko

2020-08-03 10:06 UTC, salpieiev commented
Вопрос, а либу ffmpeg ты сам сбилдил или откуда-то скачал?

2020-08-03 10:23 UTC, salpieiev commented
Меня как-то смущает эта прилетевшая MobileFFmpeg, которая стала частью нашей RDMPEG. Мы рассматривали вариант добавить необходимый функционал в нашу либу вместо интеграции thirdparty? Еще меня смущают скомпилированные бинарники. У нас есть свой скрипт для компиляции... В целом RDMPEG - это наша опенсорсная либа, которая доступна всем. Мы по лицензии это должны делать. Поэтому мне не сильно нравится подход с интеграцией огромной сердпати либы, от которой нам нужен небольшой кусок

2020-08-04 09:21 UTC, rdmeleshko commented
> Вопрос, а либу ffmpeg ты сам сбилдил или откуда-то скачал?

я взял ветку с которой работал Игорь, и взял уже его наработки (добавив функцинал которого не хватало). Касаемо твоего вопроса сбилдил ffmpeg Игорь, используя скрипты которые поставляются в mobileffmpeg: https://github.com/tanersener/mobile-ffmpeg/blob/master/ios.sh

2020-08-04 09:34 UTC, rdmeleshko commented
> Меня как-то смущает эта прилетевшая MobileFFmpeg, которая стала частью нашей RDMPEG. Мы рассматривали вариант добавить необходимый функционал в нашу либу вместо интеграции thirdparty? Еще меня смущают скомпилированные бинарники. У нас есть свой скрипт для компиляции... В целом RDMPEG - это наша опенсорсная либа, которая доступна всем. Мы по лицензии это должны делать. Поэтому мне не сильно нравится подход с интеграцией огромной сердпати либы, от которой нам нужен небольшой кусок

Наша либа на текущий момент - это third party ffmpeg + rdplayer wrapper.
В этом пулреквесте мы компиим ffmpeg с поддержкой выполнения комманд (в нашей текущей либе ffmpeg комманды не поддерживаются) + добавляются objc обертки по работе с командами ffmpeg. Твоя фраза "огромной сердпати либы, от которой нам нужен небольшой кусок" не вполне корректно. Либа которую мы добавляем это уже существующий у нас ffmpeg с добавлением нужного функционала. В либе mobileffmepg не лишних кодов которые можно просто выкусить и закинуть к нам в либу. Она нужна вся целиком. Просто перенести по классам эту либу ничего не даст кроме потери времени и сложностей с дальнейшим обновлением. Можем созвониться с Игорем и обсудить этот вопрос чтоб было быстрее.

2020-08-04 10:14 UTC, salpieiev commented
@rdif , а mp3 конвертация проходила код ривью в предыдущей реализации?

2020-08-25 06:35 UTC, rdmeleshko commented
обновил mobile ffmpeg (удалил ненужные либы) и добавил операцию обертку над mobile ffmpeg

2020-08-25 07:11 UTC, rdif commented on RDMPEG/RDMPEGConverter/RDMobileFFmpegOperation.m
> ++ (int64_t)getDurationForLocalFileAtPath:(NSString *)localFilePath{
Вроде бы, тот метод не участвует в операции? Зачем он тут?

2020-08-25 08:54 UTC, salpieiev requested changes

2020-08-25 08:54 UTC, salpieiev commented on RDMPEG/RDMPEGConverter/RDMobileFFmpegOperation.m
> +}
В целом такой функционал уже есть в RDMPEGDecoder, но еще и с поддержкой ремоутных файлов. Так что предлагаю метод полностью убрать, а там где надо использовать RDMPEGDecoder.
По-моему его нужно просто заинитить с путем, потом у инстанса вызвать [... openInput]. И вроде как свойство duration станет валидным

2020-08-25 08:54 UTC, salpieiev commented on RDMPEG/RDMPEGConverter/RDMobileFFmpegOperation.h
> +- (instancetype)initWithArguments:(NSArray *)arguments
Тут и в связанных местах лучше написать NSArray<NSString *> * (там же вроде только строковые параметры могут быть?)

2020-08-25 08:54 UTC, salpieiev commented on RDMPEG/RDMPEGDecoder/RDMPEGDecoder.m
> +//        av_freep(_avioContext->buffer);
Это случайно закомменчено?

2020-08-25 08:54 UTC, salpieiev commented on RDMPEG/RDMPEGDecoder/RDMPEGStream/RDMPEGStream+Decoder.m
> +                    codecContext->pkt_timebase = self.stream->time_base;
Чисто интересно, с чем связано это изменение? Задепрекейтили апишку?

2020-08-25 09:10 UTC, rdmeleshko commented on RDMPEG/RDMPEGDecoder/RDMPEGDecoder.m
> +//        av_freep(_avioContext->buffer);
лучше уточнить у автора,  @rdif   

коммит: 
- Dev: implemented base converter && adopt mobile ffmpeg
5e5cb91a240e689771d0c56966b37295cf9b592e

2020-08-25 09:14 UTC, rdmeleshko commented on RDMPEG/RDMPEGConverter/RDMobileFFmpegOperation.m
> ++ (int64_t)getDurationForLocalFileAtPath:(NSString *)localFilePath{
Перенес в отдельный класс

2020-08-25 09:15 UTC, rdmeleshko commented on RDMPEG/RDMPEGConverter/RDMobileFFmpegOperation.m
> +}
он там размазан и куча ненужных кодов, и сложный для этой задачи. Оставляю как есть, учитывая Игоря коммент - выношу в отдельный класс.

2020-08-25 09:16 UTC, rdmeleshko commented on RDMPEG/RDMPEGDecoder/RDMPEGStream/RDMPEGStream+Decoder.m
> +                    codecContext->pkt_timebase = self.stream->time_base;
лучше у Игоря уточнить adde3acbd90cf34bff668f38362b06a323141850

2020-08-25 09:21 UTC, rdif commented on RDMPEG/RDMPEGDecoder/RDMPEGStream/RDMPEGStream+Decoder.m
> +                    codecContext->pkt_timebase = self.stream->time_base;
да, было улучшено

2020-08-25 09:32 UTC, rdif commented on RDMPEG/RDMPEGDecoder/RDMPEGDecoder.m
> +//        av_freep(_avioContext->buffer);
лучше раскоментить и проверить, там возможны варианты.

2020-08-25 09:39 UTC, rdmeleshko commented on RDMPEG/RDMPEGDecoder/RDMPEGDecoder.m
> +//        av_freep(_avioContext->buffer);
убрал коммент и проверил - краш по памяти, потому коммент предлагаю оставить


![Screenshot 2020-08-25 at 12 36 30](https://user-images.githubusercontent.com/15983169/91158844-ea323880-e6cf-11ea-8ea4-fe9d01d0842e.png)

2020-08-25 09:47 UTC, rdif commented on RDMPEG/RDMPEGDecoder/RDMPEGDecoder.m
> +//        av_freep(_avioContext->buffer);
возможно,` if (_avioContext->buffer != NULL) { av_freep(_avioContext->buffer) }`

2020-08-25 09:49 UTC, rdif commented on RDMPEG/RDMPEGDecoder/RDMPEGDecoder.m
> +//        av_freep(_avioContext->buffer);
похоже нужно проверить где он ещё чистится

2020-08-25 09:52 UTC, rdmeleshko commented on RDMPEG/RDMPEGDecoder/RDMPEGDecoder.m
> +//        av_freep(_avioContext->buffer);
проверил, в тех местах тоже закоментировал

2020-08-25 10:05 UTC, salpieiev commented on RDMPEG/RDMPEGDecoder/RDMPEGDecoder.m
> +//        av_freep(_avioContext->buffer);
Может надо не убрать освобождение, а проверить не NULL ли буфер? И если не NULL, тогда освободить. Иначе - игнорить

2020-08-25 10:05 UTC, salpieiev commented on RDMPEG/RDMPEGDecoder/RDMPEGDecoder.m
> +//        av_freep(_avioContext->buffer);
Раньше ведь не падало, как бы утечки не было

2020-08-25 10:08 UTC, salpieiev commented on RDMPEG/RDMPEGConverter/RDMobileFFmpegOperation.m
> +}
Ну не знаю, по сути он делает то же самое, только поддерживает доп функционал. В конечном итоге вызываются те же сишные функции. Новый класс создает соблазн добавлять все больше и больше одинакового функционала, я бы не добавлял. @rdif , что думаешь?

2020-08-25 10:11 UTC, rdif commented on RDMPEG/RDMPEGConverter/RDMobileFFmpegOperation.m
> +}
переиспользовать getDurationForLocalFileAtPath в RDMPEGDecoder для локальных файлов

2020-08-25 10:12 UTC, rdif commented on RDMPEG/RDMPEGDecoder/RDMPEGDecoder.m
> +//        av_freep(_avioContext->buffer);
он не нул, судя по аутпуту там есть адресс

2020-08-25 10:14 UTC, salpieiev commented on RDMPEG/RDMPEGDecoder/RDMPEGDecoder.m
> +//        av_freep(_avioContext->buffer);
Тогда закомменченные кода нужно полностью убрать. Видимо новая функция корректно все освобождает

2020-08-25 10:15 UTC, salpieiev commented on RDMPEG/RDMPEGConverter/RDMobileFFmpegOperation.m
> +}
> переиспользовать getDurationForLocalFileAtPath в RDMPEGDecoder для локальных файлов

Что ты имеешь в виду? Перенести getDurationForLocalFileAtPath в RDMPEGDecoder? Там уже есть подобный фукнционал, он в текущем виде позволяет получить duration

2020-08-25 10:19 UTC, salpieiev requested changes

2020-08-25 10:19 UTC, salpieiev commented on .gitmodules
> +	url = git@github.com:readdle/mobile-ffmpeg.git
Уточнил у Паши этот момент, он сказал что мы для сабреп пользуемся системой 7, поэтому тут нужно использовать систему 7 вместо сабмодулей

2020-08-25 10:31 UTC, rdif commented on RDMPEG/RDMPEGConverter/RDMobileFFmpegOperation.m
> +}
я правильно понимаю, что ты предлагаешь сделать RDMPEGConverter зависимым от RDMPEGDecoder из-за этого метода? как по мне оба эти класса должны быть независимы друг от друга и использовать RDMPEGUtil что  бы не размазывать ответственности.

2020-08-25 10:47 UTC, salpieiev commented on RDMPEG/RDMPEGConverter/RDMobileFFmpegOperation.m
> +}
Нет, я предлагаю удалить этот метод, т.к. такой функционал уже есть в RDMPEGDecoder. И использовать RDMPEGDecoder там, где нужно определить длину трека. Оба класса остаются независимыми

2020-08-25 14:50 UTC, rdmeleshko commented on RDMPEG/RDMPEGConverter/RDMobileFFmpegOperation.m
> +}
RDMPEGDecoder сильно перегружен другим функционалом и тянуть его сюда не вижу смысла. 

Изначально вопрос стоял переделать mobile-ffmpeg и эта функция всех устраивала.
Теперь когда решился вопрос с mobile-ffmpeg мы переключаемся на getDurationForLocalFileAtPath ?
Можем подключить Пашу если что.

2020-08-25 14:58 UTC, rdmeleshko commented on .gitmodules
> +	url = git@github.com:readdle/mobile-ffmpeg.git
для сабреп да, но это сабмодуль RDMPEG, ты предлагаешь вынести его на уровень RD2, там где у нас находятся все сабрепы?

2020-08-25 15:14 UTC, salpieiev commented on RDMPEG/RDMPEGConverter/RDMobileFFmpegOperation.m
> +}
я не уверен что меня правильно поняли... Я предлагаю просто удалить метод. Не переносить, не модифицировать. Просто удалить. Т.к. этот функционал уже реализован в RDMPEGDecoder. После этого идем в единственное место в проекте, где используется метод getDurationForLocalFileAtPath, и пишем там примерно следующее:
decoder = [[RDMPEGDecoder alloc] initWithPath...]
[decoder openInput];
something = decoder.duration

То есть мы избавляемся от метода getDurationForLocalFileAtPath, при этом сохраняем функционал как есть. Я не предлагаю тянуть RDMPEGDecoder в этот класс. Можем созвониться чтоб все вопросы разрешить. Но уже наверное завтра

2020-08-25 15:17 UTC, salpieiev commented on .gitmodules
> +	url = git@github.com:readdle/mobile-ffmpeg.git
Нет. Надо сделать следующее - добавить Mobile FFMPEG в RDMPEG не как сабмодуль, а как сабрепу с использованием s7. То есть в репозитории RDMPEG сделать s7 init, потом s7 add Dependencies/MobileFFMPEG

2020-08-26 09:27 UTC, rdmeleshko commented on .gitmodules
> +	url = git@github.com:readdle/mobile-ffmpeg.git
добавил

2020-08-26 09:27 UTC, rdmeleshko commented on RDMPEG/RDMPEGDecoder/RDMPEGDecoder.m
> +//        av_freep(_avioContext->buffer);
похоже что действительно освобождает, убрал лишние кода

2020-08-26 09:28 UTC, rdmeleshko commented on RDMPEG/RDMPEGConverter/RDMobileFFmpegOperation.m
> +}
убрал getDurationForLocalFileAtPath и оставил RDMPEGDecoder

2020-08-26 09:32 UTC, salpieiev approved these changes
На всякий случай напоминаю, что Паша в таске еще писал что нужно происследовать возможность добавления нескольких операций конвертации одновременно (чтоб избежать проблем в многооконности).

2020-11-10 16:12 UTC, merged