Task/metal
readdle/RDMPEG pull request #4
Opened 2021-01-11 21:14 UTC by salpieiev

2021-01-18 15:17 UTC, apodrugin requested changes

2021-01-18 15:17 UTC, apodrugin commented on RDMPEG/RDMPEGRenderView/RDMPEGRenderView.m
> +    viewport.width = CGRectGetWidth(self.bounds) * [UIScreen mainScreen].scale;
Тут можно просто взять размер из drawable.texture.size, по идее.

2021-01-18 15:17 UTC, apodrugin commented on RDMPEG/RDMPEGRenderView/RDMPEGRenderView.m
> +    const double xScale = CGRectGetWidth(self.bounds) * [UIScreen mainScreen].scale / self.frameWidth;
ТУт тоже лучше брать скейл откуда-то, чем копипастить.

2021-01-19 09:24 UTC, apodrugin requested changes
Есть еще парочка предложений

2021-01-19 09:24 UTC, apodrugin commented on RDMPEG/RDMPEGRenderView/RDMPEGTextureSampler/RDMPEGTextureSampler.h
> +- (void)setupTexturesWithDevice:(id<MTLDevice>)device
Может лучше эту штуку реализовать через конструкторы конкретных реализаций этого протокола? Можно сам конструктор указать в протоколе, для того чтобы показать, что он обязателен к реализации в реализующих классах.

2021-01-19 09:24 UTC, apodrugin commented on RDMPEG/RDMPEGRenderView/RDMPEGTextureSampler/RDMPEGTextureSamplerBGRA.m
> +    if (nil == self.bgraTexture) {
Тут еще хороше тогда проверить, что размер фрейма совпадает с размером текстуры и асертнуть в противном случае.

2021-01-19 09:24 UTC, apodrugin commented on RDMPEG/RDMPEGRenderView/RDMPEGTextureSampler/RDMPEGTextureSamplerYUV.m
> +    if (nil == self.yTexture || nil == self.uTexture || nil == self.vTexture) {
Аналогичные предложения по проверке размера фрейма.

2021-01-19 18:48 UTC, salpieiev commented on RDMPEG/RDMPEGRenderView/RDMPEGTextureSampler/RDMPEGTextureSampler.h
> +- (void)setupTexturesWithDevice:(id<MTLDevice>)device
Думал так сделать, но отказался от этого по причине необходимости доступа к MTLDevice. RDMPEGRenderView инициализируется с RDMPEGTextureSampler. Получается тогда что один и тот же девайс нужно передать и в семплер, и в рендер вью. Из-а этого прийдется добавлять девайс в параметр RDMPEGRenderView. Но мне показалось это лишним, поэтому добавил отдельный метод, который RDMPEGRenderView вызовет сразу после того, как получит ссылку на девайс

2021-01-20 07:55 UTC, apodrugin approved these changes

2021-01-21 08:37 UTC, VladNaimark approved these changes

2021-01-27 15:29 UTC, merged