Task/metal fix render stall
readdle/RDMPEG pull request #5
Opened 2021-01-22 20:03 UTC by salpieiev

В этом ПР-е две темы. В целом изменений мало, поэтому скомпоновал в один ПР. Сами темы:
1. Откатил миграцию на MTKView. Это изменение пошло отдельным коммитом, лучше его так и смотреть. Сделал это по причине того, что на первый взгляд оно работает, но в определенные моменты времени рендеринг может ломаться и в логи пишутся ошибки типа:
`Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)`
Почему так происходит - непонятно, т.к. в обоих случаях реализация практически идентичная. Но в случае с Metal Layer такой проблемы нет. А в MTKView она воспроизводится довольно стабильно. Поверхностная гуглежка не помогла, а штудировать доки и форумы более детально пока не хватило сил.
2. Добавил свойство `isAbleToRender`, которое предотвращает создание (и краш) всего пайплайна для "Видео" без видеодорожки

2021-01-25 08:23 UTC, apodrugin requested changes
Есть пара предложений.

Скорее всего проблемы с MTK вьюхой связаны с тем, что мы рисуем не в explicit mode (Explicit drawing: The view redraws its contents only when you explicitly call the draw method. In this case, set paused to YES and enableSetNeedsDisplay to NO. Use this mode to create your own custom workflow) и вне метода drawRect: или делегатного метода  drawInMTKView:.

2021-01-25 08:23 UTC, apodrugin commented on RDMPEG/RDMPEGRenderView/RDMPEGRenderView.m
> +    self.contentScaleFactor = [UIScreen mainScreen].scale;
Наверное, это лучше таки брать в viewDidMoveToWindow у окна вьюхи и в этом методе еще раз обновить metalLayer.drawableSize

2021-01-25 08:23 UTC, apodrugin commented on RDMPEG/RDMPEGRenderView/RDMPEGRenderView.m
> +    if (self.isAbleToRender) {
А зачем нам вообще создавать эту вьюгу, если мы ничего не можем рендерить? Может здесь лучше просто nil вернуть и вызывающих кодах проверять размеры фрейма?

2021-01-25 12:58 UTC, salpieiev commented on RDMPEG/RDMPEGRenderView/RDMPEGRenderView.m
> +    if (self.isAbleToRender) {
Для удобства клиентских кодов. Чтоб не надо было разные проверки делать. А пусть вьюха будет такой, какая она есть. Нет видео - ок, будет черная. Даже если она добавлена на прозрачный бекграунд. Чисто гепотетически могу предположить, что это можно будет использовать для рендеринга субтитров, даже если видео нет. Сейчас конечно такой задачи пока нет, но все таки. Мы ведь открываем видеоплеер в таком случае с черным фоном

2021-01-25 13:20 UTC, apodrugin commented on RDMPEG/RDMPEGRenderView/RDMPEGRenderView.m
> +    if (self.isAbleToRender) {
ok

2021-01-25 19:08 UTC, salpieiev commented on RDMPEG/RDMPEGRenderView/RDMPEGRenderView.m
> +    self.contentScaleFactor = [UIScreen mainScreen].scale;
Проверил, как-то все равно у окна contentScaleFactor равен 1. Даже в документации написано:
`For system views, the value of this property may be 1.0 even on high resolution screens.`. Пока не вижу варианта как избавиться от `[UIScreen mainScreen].scale`

2021-01-25 19:46 UTC, salpieiev commented
> Скорее всего проблемы с MTK вьюхой связаны с тем, что мы рисуем не в explicit mode (Explicit drawing: The view redraws its contents only when you explicitly call the draw method. In this case, set paused to YES and enableSetNeedsDisplay to NO. Use this mode to create your own custom workflow) и вне метода drawRect: или делегатного метода drawInMTKView:.

Да, помогло, спасибо.

С возвращением MTKView проблема с contentScaleFactor отпала сама собой, в ней скейл правильный

2021-01-26 06:41 UTC, apodrugin approved these changes

2021-01-26 08:39 UTC, merged